2024-06-24 22:35:41 +0000 - dagster - DEBUG - __ASSET_JOB_0 - 4b614a83-ca15-472d-aa83-4905dcf98309 - 734 - LOGS_CAPTURED - Started capturing logs in process (pid: 734).
2024-06-24 22:35:41 +0000 - dagster - DEBUG - __ASSET_JOB_0 - 4b614a83-ca15-472d-aa83-4905dcf98309 - 734 - run_dbt_c7093 - STEP_START - Started execution of step "run_dbt_c7093".
2024-06-24 22:35:41 +0000 - dagster - INFO - resource:dbt - 4b614a83-ca15-472d-aa83-4905dcf98309 - run_dbt_c7093 - Executing command: dbt --no-use-colors --log-format json build --project-dir /opt/dagster/app/ecommerce_dema/utils/../../dbt --profiles-dir /opt/dagster/app/ecommerce_dema/utils/../../dbt --select fqn:*
2024-06-24 22:35:42 +0000 - dagster - INFO - resource:dbt - 4b614a83-ca15-472d-aa83-4905dcf98309 - run_dbt_c7093 - Running with dbt=1.8.2
2024-06-24 22:35:43 +0000 - dagster - INFO - resource:dbt - 4b614a83-ca15-472d-aa83-4905dcf98309 - run_dbt_c7093 - Registered adapter: postgres=1.8.2
2024-06-24 22:35:43 +0000 - dagster - INFO - resource:dbt - 4b614a83-ca15-472d-aa83-4905dcf98309 - run_dbt_c7093 - Found 1 model, 2 sources, 415 macros
2024-06-24 22:35:43 +0000 - dagster - INFO - resource:dbt - 4b614a83-ca15-472d-aa83-4905dcf98309 - run_dbt_c7093
2024-06-24 22:35:43 +0000 - dagster - INFO - resource:dbt - 4b614a83-ca15-472d-aa83-4905dcf98309 - run_dbt_c7093 - Concurrency: 4 threads (target='prod')
2024-06-24 22:35:43 +0000 - dagster - INFO - resource:dbt - 4b614a83-ca15-472d-aa83-4905dcf98309 - run_dbt_c7093
2024-06-24 22:35:43 +0000 - dagster - INFO - resource:dbt - 4b614a83-ca15-472d-aa83-4905dcf98309 - run_dbt_c7093 - 1 of 1 START sql table model public.combined_data .............................. [RUN]
2024-06-24 22:35:43 +0000 - dagster - ERROR - resource:dbt - 4b614a83-ca15-472d-aa83-4905dcf98309 - run_dbt_c7093 - 1 of 1 ERROR creating sql table model public.combined_data ..................... [ERROR in 0.11s]
2024-06-24 22:35:43 +0000 - dagster - INFO - resource:dbt - 4b614a83-ca15-472d-aa83-4905dcf98309 - run_dbt_c7093
2024-06-24 22:35:43 +0000 - dagster - INFO - resource:dbt - 4b614a83-ca15-472d-aa83-4905dcf98309 - run_dbt_c7093 - Finished running 1 table model in 0 hours 0 minutes and 0.32 seconds (0.32s).
2024-06-24 22:35:43 +0000 - dagster - INFO - resource:dbt - 4b614a83-ca15-472d-aa83-4905dcf98309 - run_dbt_c7093
2024-06-24 22:35:43 +0000 - dagster - INFO - resource:dbt - 4b614a83-ca15-472d-aa83-4905dcf98309 - run_dbt_c7093 - Completed with 1 error and 0 warnings:
2024-06-24 22:35:43 +0000 - dagster - INFO - resource:dbt - 4b614a83-ca15-472d-aa83-4905dcf98309 - run_dbt_c7093
2024-06-24 22:35:43 +0000 - dagster - ERROR - resource:dbt - 4b614a83-ca15-472d-aa83-4905dcf98309 - run_dbt_c7093 -   Database Error in model combined_data (models/combined_data.sql)
  column i.productid does not exist
  LINE 15:     ON i.productId = o.productId
                  ^
  HINT:  Perhaps you meant to reference the column "i.productId".
  compiled Code at target/run/dema_dbt/models/combined_data.sql
2024-06-24 22:35:43 +0000 - dagster - INFO - resource:dbt - 4b614a83-ca15-472d-aa83-4905dcf98309 - run_dbt_c7093
2024-06-24 22:35:43 +0000 - dagster - INFO - resource:dbt - 4b614a83-ca15-472d-aa83-4905dcf98309 - run_dbt_c7093 - Done. PASS=0 WARN=0 ERROR=1 SKIP=0 TOTAL=1
2024-06-24 22:35:44 +0000 - dagster - ERROR - __ASSET_JOB_0 - 4b614a83-ca15-472d-aa83-4905dcf98309 - 734 - run_dbt_c7093 - STEP_FAILURE - Execution of step "run_dbt_c7093" failed.

dagster_dbt.errors.DagsterDbtCliHandledRuntimeError: Handled error in the dbt CLI (return code 1)

Stack Trace:
  File "/usr/local/lib/python3.9/site-packages/dagster/_core/execution/plan/execute_plan.py", line 282, in dagster_event_sequence_for_step
    for step_event in check.generator(step_events):
  File "/usr/local/lib/python3.9/site-packages/dagster/_core/execution/plan/execute_step.py", line 501, in core_dagster_event_sequence_for_step
    for user_event in _step_output_error_checked_user_event_sequence(
  File "/usr/local/lib/python3.9/site-packages/dagster/_core/execution/plan/execute_step.py", line 186, in _step_output_error_checked_user_event_sequence
    for user_event in user_event_sequence:
  File "/usr/local/lib/python3.9/site-packages/dagster/_core/execution/plan/execute_step.py", line 91, in _process_asset_results_to_events
    for user_event in user_event_sequence:
  File "/usr/local/lib/python3.9/site-packages/dagster/_core/execution/plan/compute.py", line 195, in execute_core_compute
    for step_output in _yield_compute_results(step_context, inputs, compute_fn, compute_context):
  File "/usr/local/lib/python3.9/site-packages/dagster/_core/execution/plan/compute.py", line 164, in _yield_compute_results
    for event in iterate_with_context(
  File "/usr/local/lib/python3.9/site-packages/dagster/_utils/__init__.py", line 468, in iterate_with_context
    next_output = next(iterator)
  File "/usr/local/lib/python3.9/site-packages/dagster_dbt/asset_defs.py", line 344, in _dbt_op
    yield from _stream_event_iterator(
  File "/usr/local/lib/python3.9/site-packages/dagster_dbt/asset_defs.py", line 246, in _stream_event_iterator
    for parsed_json_line in dbt_resource.cli_stream_json(
  File "/usr/local/lib/python3.9/site-packages/dagster_dbt/core/resources.py", line 227, in cli_stream_json
    for event in execute_cli_stream(
  File "/usr/local/lib/python3.9/site-packages/dagster_dbt/core/utils.py", line 190, in execute_cli_stream
    for event in _core_execute_cli(
  File "/usr/local/lib/python3.9/site-packages/dagster_dbt/core/utils.py", line 163, in _core_execute_cli
    raise DagsterDbtCliHandledRuntimeError(messages=messages)

